### PR TITLE
m-prth

### PR DESCRIPTION
**Pull request by m-prth**
- [x] I have read the Code Of Conduct.
- [x] I have followed all the steps of submission properly.

### CODE REVIEW

**Comment by yashpaneliya** [comment]
Hey @m-prth , thank you for opening a PR.

Your PR has a merge conflict so kindly pull the recent changes and edit your PR.

Happy Hacking!!!

**Comment by m-prth** [comment]
Are changes to be done are related to the image size in the readme?

**Comment by m-prth** [comment]
Hello @yashpaneliya, please check the changes done. And tell me if there are any updates. Thank you

**Review by yashpaneliya — APPROVED** [review]

**Comment by yashpaneliya** [comment]
Thanks, @m-prth , for opening the pull request! 👏

Star ⭐  this project and [tweet](https://twitter.com/share?text=Contributed+to+awesome+projects+at+@club_gamma&url=https://clubgamma.github.io/hacktoberfest) about your contributions and tag @clubgamma.

Also join the [Discord Server](https://discord.com/invite/kjnp6wU) for future updates

Ready to merge your PR!!!

**Pull request merged**
