### PR TITLE
whonamra

### PR DESCRIPTION
**Pull request by whonamra**
~definetely not for the tshirt~ Added a new login UI.

### CODE REVIEW

**Comment by jayskhatri** [comment]
Thanks @whonamra , for opening the pull request! 👏

I'll be reviewing your pull request thoroughly

Star ⭐ this project and [tweet](https://twitter.com/share?text=Contributed+to+awesome+projects+at+@club_gamma&url=https://clubgamma.github.io/hacktoberfest) about your contributions and also you can join the [discord channel of club gamma](https://discord.gg/kjnp6wU)

**Review by jayskhatri — CHANGES_REQUESTED** [review]
Hey @whonamra, everything is ok

Now you just have to add your art in [README.md](https://github.com/clubgamma/Awesome-Flutter-Art/blob/master/README.md) in the same format.

Happy hacking!✨

**Comment by whonamra** [comment]
Will add it asap. Totally forgot it.

**Comment by jayskhatri** [comment]
Also please go through once [CONTRIBUTING.md](https://github.com/clubgamma/Awesome-Flutter-Art/blob/master/CONTRIBUTING.md) and make changes accordingly.

**Comment by whonamra** [comment]
Will make a new pull request with requested changes.

**Pull request closed without merging**
