### PR TITLE
AbhishekDoshi26

### PR DESCRIPTION
**Pull request by AbhishekDoshi26**
I have added an app named Shopping UI which has some awesome animations. It also includes use of AnimatedContainer. 

 I have read the Code Of Conduct.

 I have followed all the steps of submission properly.

### CODE REVIEW

**Review by yashpaneliya — APPROVED** [review]

**Comment by yashpaneliya** [comment]
Thanks, @AbhishekDoshi26 , for opening the pull request! 👏

Star ⭐  this project and [tweet](https://twitter.com/share?text=Contributed+to+awesome+projects+at+@club_gamma&url=https://clubgamma.github.io/hacktoberfest) about your contributions and tag @clubgamma.

Also join the [Discord Server](https://discord.com/invite/kjnp6wU)

Ready to merge your PR!!!

**Comment by AbhishekDoshi26** [comment]
> Thanks, @AbhishekDoshi26 , for opening the pull request! 👏
> 
> Star ⭐ this project and [tweet](https://twitter.com/share?text=Contributed+to+awesome+projects+at+@club_gamma&url=https://clubgamma.github.io/hacktoberfest) about your contributions and tag @clubgamma.
> 
> Also join the [Discord Server](https://discord.com/invite/kjnp6wU)
> 
> Ready to merge your PR!!!

Great! Thanks.
@yashpaneliya when will it be merged?

**Comment by AbhishekDoshi26** [comment]
@yashpaneliya and if I have more projects to add, should I create folders in my folder?

**Comment by yashpaneliya** [comment]
> @yashpaneliya and if I have more projects to add, should I create folders in my folder?

Yes sure, you can add your other work inside your folder!!

**Comment by yashpaneliya** [comment]
Hello contributor👋,

As we all know that Hacktoberfest-2020 is ended. Hope you enjoyed it a lot and made some awesome contributions. 
So now it's time for schwags🎁🤩

**Send your email (linked with your GitHub account) in the reply of this comment. Mention any one of the maintainers (@yashpaneliya @rudrabarad @harshptl14 @chirayu-joshi @dhruvpatel1706 ) in the reply.**

**We'll send a form on the email you'll provide. Please reply ASAP.**

Join [Club Gamma Discord](https://discord.com/invite/kjnp6wU) for future updates.

**Comment by AbhishekDoshi26** [comment]
Here's my email adoshi26.ad@gmail.com

@yashpaneliya

Abhishek Doshi

**Pull request merged**
